name: kalori_app
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:

  flutter:
    sdk: flutter
  confetti: ^0.7.0  
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.64.0
  cupertino_icons: ^1.0.8
  
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  firebase_auth_web: ^5.8.13      
  cloud_firestore: ^4.12.0       



dev_dependencies:
 
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:


  uses-material-design: true

  